[package]
name = "spawner-meta"
version = "0.1.0"
edition = "2018"
publish = false
authors = [
    "Micha Vie <micha@peerme.io>",
    "Spawnable <hello@spawnable.io>",
]

[dev-dependencies]

[dependencies.spawner]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.57.1"
